<a href="https://colab.research.google.com/github/AlexandreMachineLearning/Regressao-linear-Ridge/blob/main/Q_6_Regressao_linear_Ridge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Usando cross-validation leave-one-out e um algoritmo de regressão linear Ridge, com regularização R2 e parâmetro de regularização igual a 1.7, calcule o RMSE médio de treino e validação para os dados no arquivo regressao_q6.csv

Passo 1 - Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



Passo 2 - Criação e Carregamento do dataframe

In [2]:
regression_df=pd.read_csv('/content/regressao_Q6.csv')

In [3]:
regression_df.head()

x0        x1        x2  ...        x8        x9      target
0 -0.351837  0.719462  0.862522  ...  1.306696  0.450022  170.471696
1 -0.309565  0.786033  1.175365  ...  1.334661 -0.267235  151.023999
2 -1.808729 -0.581660 -0.052200  ...  0.841643 -1.186626 -268.606299
3 -0.386627  0.991724  0.234672  ...  0.933481  1.280705  180.737656
4 -0.879158  0.106556  0.775418  ...  1.383563 -1.152509  -38.200673

[5 rows x 11 columns]

In [4]:
regression_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x0      1100 non-null   float64
 1   x1      1100 non-null   float64
 2   x2      1100 non-null   float64
 3   x3      1100 non-null   float64
 4   x4      1100 non-null   float64
 5   x5      1100 non-null   float64
 6   x6      1100 non-null   float64
 7   x7      1100 non-null   float64
 8   x8      1100 non-null   float64
 9   x9      1100 non-null   float64
 10  target  1100 non-null   float64
dtypes: float64(11)
memory usage: 94.7 KB


In [5]:
print(regression_df.isnull().sum())

x0        0
x1        0
x2        0
x3        0
x4        0
x5        0
x6        0
x7        0
x8        0
x9        0
target    0
dtype: int64


Passo 3 - Separação dos dados

In [6]:
X = regression_df.drop('target',axis=1).values
Y = regression_df['target'].values

In [7]:
X

array([[-0.35183672,  0.71946212,  0.86252193, ...,  0.60717393,
         1.30669552,  0.45002248],
       [-0.30956458,  0.78603289,  1.17536461, ...,  0.56896766,
         1.33466106, -0.26723532],
       [-1.80872907, -0.58165957, -0.05219979, ..., -0.6773723 ,
         0.84164275, -1.18662595],
       ...,
       [-1.15542263, -0.20606577,  0.63607072, ..., -0.35719131,
         1.45067207,  0.04963575],
       [-2.4141733 , -0.99367352,  0.56605337, ..., -1.21029804,
         1.11518776, -1.45009927],
       [-0.79442169,  0.66654512,  0.62789042, ...,  0.00957522,
         1.28425117, -0.05887021]])

In [8]:
Y

array([ 170.47169559,  151.02399939, -268.60629935, ...,  -57.4578359 ,
       -271.62251427,   77.61022631])

Passo 4 - Separação dos dados de treinamento e teste

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge

In [10]:
X_treino, X_teste, Y_treino, Y_teste = train_test_split(X,Y, test_size=0.3, shuffle=True,random_state=0)

In [11]:
X_treino.size

7700

In [12]:
X_teste.size

3300

Passo 5 - Previsões

In [13]:
modelo1= Ridge(alpha=1.7)
modelo1.fit(X_treino,Y_treino)

Ridge(alpha=1.7)

In [14]:
Y_previsto = modelo1.predict(X_teste)

Passo 6 - Cálculo do MAE e do RMSE

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE_sol = mean_absolute_error(Y_teste,Y_previsto)
RMSE_sol = np.sqrt(mean_squared_error(Y_teste,Y_previsto))

In [16]:
Y_teste

array([ 5.22501291e+02,  9.27629926e+01,  4.58794860e+02,  3.45809874e+02,
        9.83054999e+02, -5.42563174e+02,  1.95020513e+02, -2.99841533e+02,
       -1.91303097e+02, -7.37350079e+02, -2.46578030e+02,  3.25492902e+02,
        1.25686522e+02,  4.50207337e+02, -5.34061758e+02, -3.44406336e+02,
        1.24111842e+02, -3.74847308e+02,  9.67047791e+02,  8.99145282e+02,
        6.81235136e+02,  1.48050447e+02,  4.23802581e+02, -9.46129624e+02,
       -4.58128811e+02, -1.42266545e+02,  7.76102263e+01, -3.84541922e+02,
       -5.49083937e+02,  3.37262110e+02,  2.62068122e+02,  3.37188041e+02,
        3.81771365e+02,  4.65996390e+01,  2.58693252e+01, -5.53865042e+02,
        6.91607869e+01,  8.48910169e+02,  1.96230237e+02,  3.86500697e+02,
        6.52598716e-01,  2.16158216e+02, -3.07287567e+02, -2.11332000e+02,
        8.11445382e+02, -4.58955800e+02,  1.10945587e+02,  7.59134598e+02,
        6.78633700e+02, -1.60917602e+02,  3.01973709e+02, -4.35075245e+02,
       -3.45450828e+02,  

In [17]:
Y_previsto

array([ 5.30905338e+02,  1.06873833e+02,  4.80604826e+02,  3.46574295e+02,
        9.69208502e+02, -5.45133455e+02,  2.14608420e+02, -2.66245788e+02,
       -1.80019168e+02, -7.20943565e+02, -2.36952374e+02,  3.45698872e+02,
        1.19535573e+02,  4.44242190e+02, -5.35022675e+02, -2.98249692e+02,
        1.41440024e+02, -3.52372642e+02,  9.27373066e+02,  9.30739498e+02,
        6.79487441e+02,  1.65942403e+02,  4.61952028e+02, -8.57930022e+02,
       -4.12633693e+02, -1.44452232e+02,  5.71399062e+01, -3.58120664e+02,
       -5.16464505e+02,  3.55800453e+02,  2.38698297e+02,  3.13918750e+02,
        4.14691633e+02,  1.72618382e+01,  5.67790720e+01, -5.35005410e+02,
        3.12578507e+01,  7.84107381e+02,  1.77373103e+02,  3.43534529e+02,
        2.59259780e+01,  2.29101754e+02, -3.22876994e+02, -2.29513759e+02,
        7.66677584e+02, -4.55765559e+02,  1.02348271e+02,  7.11548379e+02,
        7.00118812e+02, -1.22292970e+02,  3.29169707e+02, -4.44757903e+02,
       -3.51493153e+02,  

In [18]:
print('MAE={:0.4f}'.format(MAE_sol))
print('RMSE={:0.4f}'.format(RMSE_sol))

MAE=22.3500
RMSE=27.9994


In [19]:
score = modelo1.score(X_treino,Y_treino)

In [20]:
score

0.9953787265947541